# Traning 
epochs: 100
batch_size: 4
lr_backbone: 0.0001
lr_head: 0.001
weight_decay: 0.01
lr_decay: 0.99

# Model
maxlen: 60
mlp_ratio: 2
depth: 5
num_heads: 8
att_fuse: True
num_joints: 2
dim_bbox : 2
dim_feat: 512
dim_rep: 512
hidden_dim: 2048
dropout_ratio: 0.5

# Data
data_path: data/jaad_database.pkl
chk_path: checkpoints/latest_epoch.bin
clip_len: 60
action_classes: 2 #0 : not crossing
                  #1 : crossing
